services:
  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    environment:
      - username=admin
      - password=b1gl1nux_collabora
      - aliasgroup1=http://GET_IP:5731,http://collabora
      - dictionaries=en_US es_ES pt_BR pt_PT
      - extra_params=--o:welcome.enable=false --o:coolwsd:service:allowed_languages=en_US,es_ES,pt_BR,pt_PT --o:ssl.enable=false
    ports:
      - "9980:9980"
    cap_add:
      - MKNOD
      - SYS_ADMIN
    volumes:
      - ${HOME}/Docker/Nextcloud-Plus/Collabora/config/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9980"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - collabora-net

networks:
  collabora-net:
    driver: bridge
