services:
  nextcloud_db:
    image: postgres:16-alpine
    container_name: nextcloud_db
    restart: always
    volumes:
      - ${HOME}/Docker/Nextcloud-Plus/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=b1gl1nux@db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "5432"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - nextcloud-net

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    volumes:
      - ${HOME}/Docker/Nextcloud-Plus/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_PASSWORD=b1gl1nux@db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=biglinux
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=b1gl1nux@redis
      - NEXTCLOUD_TRUSTED_DOMAINS=GET_IP
      - NEXTCLOUD_TRUSTED_PROXIES=collabora
    depends_on:
      - nextcloud_db
      - redis
    ports:
      - "8286:80/tcp"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - nextcloud-net
      - collabora-net

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass b1gl1nux@redis --appendonly yes
    volumes:
      - ${HOME}/Docker/Nextcloud-Plus/redis:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    name: nextcloud-net
  collabora-net:
    external: true
